### ISSUE TITLE
lost of data

### ISSUE THREAD

**Issue by pollons** [toolthis/flashme#1]
I download your app FlashMe two months ago. I had a deck with 250 cards, called words, and today impovisally it disappeared without press nothing. Does a way exist to recover it ? Please, it is very important for me.

**Comment by betsegaw** [comment]
Hey,

I am really sorry to hear that you are having issues. I want to get this fixed up for you ASAP.

The first step is to make sure that we save your data from whatever is going on. Can you navigate to this folder on your PC and see if you can find a folder that has "flashme" in it?

C:\Users\[yourUserName]\AppData\Local\Packages

If so navigate to the folder and inside, you will find a folder named "LocalState", in which you should be able to find a bunch of files with weird names. Copy them out and save them else where on your desktop. They are the actual decks that FlashMe saves your data in.

Let me know when you have had a chance to try this out.

Again, apologies that you are having issues and hopefully, we will have this resolved soon.

Thanks,
Beta

**Comment by pollons** [comment]
Thank you for your promp help. I follow your instructions and I probably find something.  You can find the picture attached below.
![cattura](https://cloud.githubusercontent.com/assets/25776917/22947250/3eea7b10-f2f2-11e6-8dcf-daf4f7c960a6.PNG)

**Comment by betsegaw** [comment]
Great, all your files are there. Copy them out to a safe location on your desktop before we try to fix this. You only need to copy the blue files from the screen shots.

Once you have safely copied those files out of there, uninstall the app and reinstall it. 

Then from the desktop, copy back the blue files and try to start the app again.

Let me know how that goes. Again, I am sorry that you are having issues but the good news is that your data is safe, which is the most important part. 

Again, make sure you copy all of the blue files *before* you uninstall the app.

**Comment by pollons** [comment]
After that I reinstall the app, where do I copy back the blue files? In the same folder where they are now?
Uninstall the app it's the only way to recover my data? because I have other deks in my app... and I wouldn't lose them

**Comment by betsegaw** [comment]
Hmmm. Okay, before we go down that route we can try another. How many decks do you have? Are they the same number as the blue colored files?

**Comment by betsegaw** [comment]
Hmmm. Okay, before we go down that route we can try another. How many decks do you have? Are they the same number as the blue colored files?

**Comment by pollons** [comment]
I have 7 decks in my app and they are the same of the blue colored files in
the folder. Does this mean that the datas of the missing deck are lost?
 Then also one of the two yellow folder above the blue files contain some
file.

2017-02-15 3:40 GMT+00:00 Betsegaw Tadele <notifications@github.com>:

**Comment by betsegaw** [comment]
What are the files in the "obj" directory?

**Comment by pollons** [comment]
There are some files..

2017-02-15 19:13 GMT+00:00 Betsegaw Tadele <notifications@github.com>:

**Comment by betsegaw** [comment]
What are the files like?

**Comment by pollons** [comment]
It's something related to FlashMe app but I can't open them because when I
try appear this advice

2017-02-16 0:34 GMT+00:00 Betsegaw Tadele <notifications@github.com>:

**Comment by betsegaw** [comment]
If the number of files that are blue is the same as the number of decks that are viewable from the app, then I am sorry, but your data is not there.

Was there anything weird when you closed the app the last time you saw the deck? Maybe a Windows update restarted it? 

Again, I really want to apologize for the loss of your cards. This scenario should never happen and we will continually improve the app to make sure that this doesn't happen again.

**Comment by pollons** [comment]
When I closed the app there was nothing weird, then I turn off my laptop
and it's possible that the system did  an update because sometimes it does
it automatically. Do you know some programme to recover lost data?

2017-02-20 10:39 GMT+00:00 Betsegaw Tadele <notifications@github.com>:

**Comment by betsegaw** [comment]
I can't really recommend any of the top of my head, it's been a long time since I had to try to recover any file.

**Comment by betsegaw** [comment]
Closing this issue since it is most likely an OS related issue.
